# Generated by Django 6.0.6 on 2026-06-22 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('super_admin', 'Super Admin'), ('principal', 'Principal'), ('vice_principal', 'Vice Principal'), ('bursar', 'Bursar'), ('teacher', 'Teacher'), ('student', 'Student'), ('parent', 'Parent'), ('alumni', 'Alumni'), ('nurse', 'School Nurse'), ('counsellor', 'Counsellor')], db_index=True, default='student', max_length=20),
        ),
    ]
